-- ============================================================
-- Schéma de base de données BinkEdu pour Supabase
-- À exécuter dans : Supabase > SQL Editor > New query > Run
-- ============================================================

-- Table des écoles
create table if not exists schools (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  director text,
  phone text,
  email text,
  authorization_number text,
  academic_year text default '2025-2026',
  primary_color text default '#1e40af',
  secondary_color text default '#3b82f6',
  subscription_status text default 'active',
  subscription_end_date date,
  created_at timestamptz default now()
);

-- Table des membres (utilisateurs rattachés à une école)
create table if not exists school_members (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) on delete cascade,
  username text,
  role text default 'admin',
  full_name text,
  assigned_class text,
  user_id text,
  created_at timestamptz default now()
);

-- Table des élèves
create table if not exists students (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  gender text default 'M',
  birth_date date,
  birth_place text,
  address text,
  parent_name text,
  mother_name text,
  phone text,
  class_name text,
  enrollment_date date,
  status text default 'active',
  created_at timestamptz default now()
);

-- Table des classes
create table if not exists classes (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) on delete cascade,
  name text,
  level text,
  section text,
  teacher_name text,
  capacity integer default 50,
  created_at timestamptz default now()
);

-- Table des notes
create table if not exists grades (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) on delete cascade,
  student_id bigint references students(id) on delete cascade,
  class_id bigint default 0,
  trimester integer,
  french_resource numeric default 0,
  french_competence numeric default 0,
  math_resource numeric default 0,
  math_competence numeric default 0,
  arabic numeric default 0,
  religious_education numeric default 0,
  history numeric default 0,
  geography numeric default 0,
  ist numeric default 0,
  ve numeric default 0,
  vdm numeric default 0,
  copy numeric default 0,
  arts numeric default 0,
  conduct numeric default 0,
  total numeric default 0,
  average numeric default 0,
  created_at timestamptz default now()
);

-- Table des mensualités
create table if not exists monthly_fees (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) on delete cascade,
  student_id bigint references students(id) on delete cascade,
  month text,
  amount numeric,
  paid boolean default false,
  payment_date date,
  academic_year text,
  created_at timestamptz default now()
);

-- Table de comptabilité
create table if not exists accounting_entries (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) on delete cascade,
  entry_type text,
  category text,
  description text,
  amount numeric,
  entry_date date,
  created_at timestamptz default now()
);

-- Table du personnel
create table if not exists staff (
  id bigint generated by default as identity primary key,
  school_id bigint references schools(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  address text,
  phone text,
  position text,
  gross_salary numeric default 0,
  advance numeric default 0,
  credit numeric default 0,
  loan_repayment numeric default 0,
  retirement numeric default 0,
  mutual numeric default 0,
  trimf numeric default 0,
  tontine numeric default 0,
  created_at timestamptz default now()
);

-- ============================================================
-- Sécurité (Row Level Security)
-- Toute personne CONNECTÉE (authentifiée) peut lire/écrire.
-- Les visiteurs non connectés n'ont AUCUN accès.
-- ============================================================

alter table schools enable row level security;
alter table school_members enable row level security;
alter table students enable row level security;
alter table classes enable row level security;
alter table grades enable row level security;
alter table monthly_fees enable row level security;
alter table accounting_entries enable row level security;
alter table staff enable row level security;

create policy "authenticated_full_access" on schools for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated_full_access" on school_members for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated_full_access" on students for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated_full_access" on classes for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated_full_access" on grades for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated_full_access" on monthly_fees for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated_full_access" on accounting_entries for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "authenticated_full_access" on staff for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
